/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    scopes: Scope;
    inventory: Inventory;
    repairs: Repair;
    evaluation: Evaluation;
    quotation: Quotation;
    invoices: Invoice;
    brands: Brand;
    manufacturers: Manufacturer;
    companies: Company;
    users: User;
    media: Media;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    scopes: ScopesSelect<false> | ScopesSelect<true>;
    inventory: InventorySelect<false> | InventorySelect<true>;
    repairs: RepairsSelect<false> | RepairsSelect<true>;
    evaluation: EvaluationSelect<false> | EvaluationSelect<true>;
    quotation: QuotationSelect<false> | QuotationSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    manufacturers: ManufacturersSelect<false> | ManufacturersSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Core workflow stages involved in handling service requests, from initial scoping to final invoicing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scopes".
 */
export interface Scope {
  id: number;
  code?: string | null;
  name: string;
  /**
   * Select the company that owns this scope
   */
  company: number | Company;
  type: 'rigid' | 'flexible';
  modelNumber: string;
  serialNumber: string;
  brand: number | Brand;
  manufacturer: number | Manufacturer;
  status?: ('active' | 'inactive' | 'under_repair' | 'retired') | null;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  receivedDate?: string | null;
  createdBy?: (number | null) | User;
  /**
   * Click the button below to create a new evaluation for this scope
   */
  createEvaluation?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage companies and their details
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  name: string;
  phoneNumber?: number | null;
  email?: string | null;
  address?: string | null;
  mofNumber?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage inventory items and track stock levels
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  title: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage inventory items and track stock levels
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manufacturers".
 */
export interface Manufacturer {
  id: number;
  companyName?: string | null;
  companyEmail?: string | null;
  companyPhone?: string | null;
  country:
    | 'CA'
    | 'CN'
    | 'EG'
    | 'FR'
    | 'DE'
    | 'IT'
    | 'JP'
    | 'LB'
    | 'RU'
    | 'SA'
    | 'SG'
    | 'ZA'
    | 'ES'
    | 'SE'
    | 'CH'
    | 'AE'
    | 'GB'
    | 'US';
  companyWebsite?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage users and their details
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  role: 'admin' | 'user';
  /**
   * Whether this user can log in
   */
  isActive?: boolean | null;
  phone?: string | null;
  department?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * Manage inventory items and track stock levels
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory".
 */
export interface Inventory {
  id: number;
  /**
   * Name of the part
   */
  partName: string;
  /**
   * Unique part number
   */
  partNumber: string;
  /**
   * Length of the part (if applicable)
   */
  length?: number | null;
  /**
   * Diameter of the part (if applicable)
   */
  diameter?: number | null;
  /**
   * Country of origin
   */
  country?: string | null;
  /**
   * Select the manufacturer of this specific part
   */
  partManufacturer?: (number | null) | Manufacturer;
  scopeType: 'rigid' | 'flexible';
  /**
   * Current stock quantity
   */
  quantity?: number | null;
  /**
   * Minimum quantity before reorder alert
   */
  reorderPoint?: number | null;
  /**
   * Cost per unit
   */
  unitCost?: number | null;
  /**
   * Selling price per unit
   */
  unitPrice?: number | null;
  /**
   * Storage location
   */
  location?: string | null;
  status?: ('inStock' | 'lowStock' | 'outOfStock' | 'discontinued') | null;
  lastUpdated?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Core workflow stages involved in handling service requests, from initial scoping to final invoicing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "repairs".
 */
export interface Repair {
  id: number;
  repairNumber: string;
  /**
   * Only scopes with approved quotations are shown
   */
  scope: number | Scope;
  /**
   * Only evaluations with scopes that have approved quotations are shown
   */
  evaluation?: (number | null) | Evaluation;
  quotation?: (number | null) | Quotation;
  status: 'pending' | 'done' | 'notDone';
  partsUsed?:
    | {
        /**
         * Select a part from inventory. Unit cost will be automatically populated.
         */
        part: number | Inventory;
        quantityUsed: number;
        /**
         * Unit cost is automatically populated from the selected part
         */
        unitCost?: number | null;
        totalCost?: number | null;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  startDate?: string | null;
  completionDate?: string | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Core workflow stages involved in handling service requests, from initial scoping to final invoicing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evaluation".
 */
export interface Evaluation {
  id: number;
  evaluationNumber: string;
  scope: number | Scope;
  /**
   * Scope code (auto-populated from scope relationship)
   */
  scopeCode?: string | null;
  /**
   * Scope name (auto-populated from scope relationship)
   */
  scopeName?: string | null;
  /**
   * Model number (auto-populated from scope relationship)
   */
  modelNumber?: string | null;
  /**
   * Serial number (auto-populated from scope relationship)
   */
  serialNumber?: string | null;
  /**
   * Current status of the evaluation
   */
  status: 'pending' | 'done' | 'notDone';
  evaluationDate?: string | null;
  problemsIdentified: string;
  recommendedActions?: string | null;
  /**
   * Customer does not see this
   */
  estimatedCost?: number | null;
  /**
   * Estimated repair duration in days
   */
  estimatedDuration?: number | null;
  evaluatedBy?: (number | null) | User;
  notes?: string | null;
  /**
   * Click the button below to create a new quotation for this evaluation
   */
  createQuotation?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Core workflow stages involved in handling service requests, from initial scoping to final invoicing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotation".
 */
export interface Quotation {
  id: number;
  quotationNumber: string;
  scope: number | Scope;
  /**
   * Scope code (auto-populated from scope relationship)
   */
  scopeCode?: string | null;
  /**
   * Scope name (auto-populated from scope relationship)
   */
  scopeName?: string | null;
  /**
   * Model number (auto-populated from scope relationship)
   */
  modelNumber?: string | null;
  /**
   * Serial number (auto-populated from scope relationship)
   */
  serialNumber?: string | null;
  /**
   * Select an evaluation that belongs to the selected scope. The dropdown will show all evaluations, but only scope-related ones are valid.
   */
  evaluation?: (number | null) | Evaluation;
  quotationDate?: string | null;
  offerValidity?: string | null;
  /**
   * Delivery period in days
   */
  deliveryPeriod?: number | null;
  problems: string;
  serviceType: 'repair' | 'maintenance' | 'calibration' | 'inspection';
  /**
   * Total quotation price
   */
  price: number;
  discount?: number | null;
  quotationStatus: 'pending' | 'approved' | 'denied';
  notes?: string | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Core workflow stages involved in handling service requests, from initial scoping to final invoicing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number;
  invoiceNumber: string;
  scope: number | Scope;
  repair?: (number | null) | Repair;
  quotation?: (number | null) | Quotation;
  invoiceDate?: string | null;
  dueDate?: string | null;
  status: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';
  /**
   * Price per unit
   */
  unitPrice: number;
  totalPrice?: number | null;
  /**
   * Same as total price
   */
  subtotal?: number | null;
  /**
   * 11% of subtotal
   */
  tax?: number | null;
  /**
   * 11% of subtotal in LBP
   */
  taxLebanese?: number | null;
  /**
   * Subtotal + Tax
   */
  totalDue?: number | null;
  paymentTerms?: string | null;
  /**
   * Show TVA amount in Lebanese Pounds (LBP) in addition to USD
   */
  showTVAInLBP?: boolean | null;
  notes?: string | null;
  createdBy?: (number | null) | User;
  /**
   * Generated invoice PDF. Use the API endpoint /api/invoices/{id}/generate-pdf to generate and download the PDF.
   */
  pdf?: (number | null) | Media;
  /**
   * S3 URL of the generated PDF
   */
  pdfUrl?: string | null;
  /**
   * Timestamp when PDF was last generated
   */
  pdfGeneratedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Media files associated with scopes, repairs, and records.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'scopes';
        value: number | Scope;
      } | null)
    | ({
        relationTo: 'inventory';
        value: number | Inventory;
      } | null)
    | ({
        relationTo: 'repairs';
        value: number | Repair;
      } | null)
    | ({
        relationTo: 'evaluation';
        value: number | Evaluation;
      } | null)
    | ({
        relationTo: 'quotation';
        value: number | Quotation;
      } | null)
    | ({
        relationTo: 'invoices';
        value: number | Invoice;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'manufacturers';
        value: number | Manufacturer;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scopes_select".
 */
export interface ScopesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  company?: T;
  type?: T;
  modelNumber?: T;
  serialNumber?: T;
  brand?: T;
  manufacturer?: T;
  status?: T;
  description?: T;
  receivedDate?: T;
  createdBy?: T;
  createEvaluation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory_select".
 */
export interface InventorySelect<T extends boolean = true> {
  partName?: T;
  partNumber?: T;
  length?: T;
  diameter?: T;
  country?: T;
  partManufacturer?: T;
  scopeType?: T;
  quantity?: T;
  reorderPoint?: T;
  unitCost?: T;
  unitPrice?: T;
  location?: T;
  status?: T;
  lastUpdated?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "repairs_select".
 */
export interface RepairsSelect<T extends boolean = true> {
  repairNumber?: T;
  scope?: T;
  evaluation?: T;
  quotation?: T;
  status?: T;
  partsUsed?:
    | T
    | {
        part?: T;
        quantityUsed?: T;
        unitCost?: T;
        totalCost?: T;
        id?: T;
      };
  notes?: T;
  startDate?: T;
  completionDate?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evaluation_select".
 */
export interface EvaluationSelect<T extends boolean = true> {
  evaluationNumber?: T;
  scope?: T;
  scopeCode?: T;
  scopeName?: T;
  modelNumber?: T;
  serialNumber?: T;
  status?: T;
  evaluationDate?: T;
  problemsIdentified?: T;
  recommendedActions?: T;
  estimatedCost?: T;
  estimatedDuration?: T;
  evaluatedBy?: T;
  notes?: T;
  createQuotation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotation_select".
 */
export interface QuotationSelect<T extends boolean = true> {
  quotationNumber?: T;
  scope?: T;
  scopeCode?: T;
  scopeName?: T;
  modelNumber?: T;
  serialNumber?: T;
  evaluation?: T;
  quotationDate?: T;
  offerValidity?: T;
  deliveryPeriod?: T;
  problems?: T;
  serviceType?: T;
  price?: T;
  discount?: T;
  quotationStatus?: T;
  notes?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  invoiceNumber?: T;
  scope?: T;
  repair?: T;
  quotation?: T;
  invoiceDate?: T;
  dueDate?: T;
  status?: T;
  unitPrice?: T;
  totalPrice?: T;
  subtotal?: T;
  tax?: T;
  taxLebanese?: T;
  totalDue?: T;
  paymentTerms?: T;
  showTVAInLBP?: T;
  notes?: T;
  createdBy?: T;
  pdf?: T;
  pdfUrl?: T;
  pdfGeneratedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manufacturers_select".
 */
export interface ManufacturersSelect<T extends boolean = true> {
  companyName?: T;
  companyEmail?: T;
  companyPhone?: T;
  country?: T;
  companyWebsite?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  phoneNumber?: T;
  email?: T;
  address?: T;
  mofNumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  isActive?: T;
  phone?: T;
  department?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  companyName: string;
  companyPhone: string;
  companyEmail: string;
  mofNumber: string;
  /**
   * Exchange rate: $1 = X L.L.
   */
  dollarRate: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  companyName?: T;
  companyPhone?: T;
  companyEmail?: T;
  mofNumber?: T;
  dollarRate?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}